num_gpus: 8
local_batch_size: 32
lr: 0.1
num_epochs: 120
pretrained: false
finetune: false

num_classes: 101
image_size: 224
dataset_name: Food101N

setting: gpu${num_gpus}_batch${local_batch_size}_${scheduler.lr.name}${lr}_epoch${num_epochs}

load_model_path: ../checkpoint/best_valid_avg_top1.pth
# Saving Features and Pseudo Labels
save_root: ../reports
save_filename: baseline

data:
    train:
        imglist_type: ListImglist
        imglist_path: ../imglists/train.txt
        root: ../data/Food-101N/images
        pseudo_root: ../pseudo/Food101N/Food101N_cnn_test_score
        skip_broken: false
        reader: DirectReader
        transform_extra:
            SmoothSingleLabel:
                epsilon: 0.0
        transform_batch:
            __clear__: true
            TensorCuda: {}
            BatchFancyPCA: {}
            BatchNormalize:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]


    valid:
        imglist_type: ListImglist
        imglist_path: ../imglists/val.txt
        root: ../data/Food-101/images
        reader: DirectReader
        skip_broken: false
        #shuffle: false
        transform_extra:
            SmoothSingleLabel:
                epsilon: 0.0
        transform_batch:
            __clear__: true
            TensorCuda: {}
            BatchFancyPCA: {}
            BatchNormalize:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

network:
    verbose: true
    names: [main]
    main:
        name: gluon.resnet50_v1b
        kwargs:
            zero_gamma: true
            num_classes: '@{num_classes}'
        init:
            load_model_zoo:
                use: '@{pretrained}'
                model_name: '@{network.main.name}'
                load_from: disk
                version: 1.1.1
            load_ckpt:
                use: '@{finetune}'
                network_name: main
                ckpt: '@{load_model_path}'


scheduler:
    lr:
        __clear__: true
        name: CosineScheduler
        unit_length: epoch
        kwargs:
            base_value: '@{lr}'
            total_steps: '@{num_epochs}'
            warmup_steps: 5
